package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuisnessService generated by hbm2java
 */
@Entity
@Table(name = "buisness_service", catalog = "heroku_54640e8309ac0d5")
public class BuisnessService implements java.io.Serializable {

	private Integer id;
	private Business business;
	private String description;
	private String name;
	private Set<BranchService> branchServices = new HashSet<BranchService>(0);

	public BuisnessService() {
	}

	public BuisnessService(String name) {
		this.name = name;
	}

	public BuisnessService(Business business, String description, String name,
			Set<BranchService> branchServices) {
		this.business = business;
		this.description = description;
		this.name = name;
		this.branchServices = branchServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buisness_id")
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buisnessService")
	public Set<BranchService> getBranchServices() {
		return this.branchServices;
	}

	public void setBranchServices(Set<BranchService> branchServices) {
		this.branchServices = branchServices;
	}

}
