package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SpecialEvent generated by hbm2java
 */
@Entity
@Table(name = "special_event", catalog = "heroku_54640e8309ac0d5")
public class SpecialEvent implements java.io.Serializable {

	private Integer id;
	private BranchService branchService;
	private Boolean toClose;
	private Boolean toOpen;
	private String date;
	private Date start;
	private Date end;
	private String description;
	private String message;

	public SpecialEvent() {
	}

	public SpecialEvent(BranchService branchService, Boolean toClose,
			Boolean toOpen, String date, Date start, Date end,
			String description, String message) {
		this.branchService = branchService;
		this.toClose = toClose;
		this.toOpen = toOpen;
		this.date = date;
		this.start = start;
		this.end = end;
		this.description = description;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_service_id")
	public BranchService getBranchService() {
		return this.branchService;
	}

	public void setBranchService(BranchService branchService) {
		this.branchService = branchService;
	}

	@Column(name = "to_close")
	public Boolean getToClose() {
		return this.toClose;
	}

	public void setToClose(Boolean toClose) {
		this.toClose = toClose;
	}

	@Column(name = "to_open")
	public Boolean getToOpen() {
		return this.toOpen;
	}

	public void setToOpen(Boolean toOpen) {
		this.toOpen = toOpen;
	}

	@Column(name = "date", length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start", length = 0)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end", length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "message", length = 100)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
