package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "heroku_54640e8309ac0d5")
public class Users implements java.io.Serializable {

	private Integer id;
	private Queue queue;
	private String ssn;
	private String mobile;
	private String gpsLat;
	private String gpsLong;
	private int rating;
	private String password;
	private String email;
	private String username;
	private boolean emailVerified;
	private String nickname;
	private String tenant;
	private String connection;
	private String debug;
	private Set<UserBranchServicePrivilege> userBranchServicePrivileges = new HashSet<UserBranchServicePrivilege>(
			0);
	private Set<Queue> queues = new HashSet<Queue>(0);

	public Users() {
	}

	public Users(int rating, String username, boolean emailVerified) {
		this.rating = rating;
		this.username = username;
		this.emailVerified = emailVerified;
	}

	public Users(Queue queue, String ssn, String mobile, String gpsLat,
			String gpsLong, int rating, String password, String email,
			String username, boolean emailVerified, String nickname,
			String tenant, String connection, String debug,
			Set<UserBranchServicePrivilege> userBranchServicePrivileges,
			Set<Queue> queues) {
		this.queue = queue;
		this.ssn = ssn;
		this.mobile = mobile;
		this.gpsLat = gpsLat;
		this.gpsLong = gpsLong;
		this.rating = rating;
		this.password = password;
		this.email = email;
		this.username = username;
		this.emailVerified = emailVerified;
		this.nickname = nickname;
		this.tenant = tenant;
		this.connection = connection;
		this.debug = debug;
		this.userBranchServicePrivileges = userBranchServicePrivileges;
		this.queues = queues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "next_queue_id")
	public Queue getQueue() {
		return this.queue;
	}

	public void setQueue(Queue queue) {
		this.queue = queue;
	}

	@Column(name = "ssn", length = 9)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "gps_lat", length = 45)
	public String getGpsLat() {
		return this.gpsLat;
	}

	public void setGpsLat(String gpsLat) {
		this.gpsLat = gpsLat;
	}

	@Column(name = "gps_long", length = 45)
	public String getGpsLong() {
		return this.gpsLong;
	}

	public void setGpsLong(String gpsLong) {
		this.gpsLong = gpsLong;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email_verified", nullable = false)
	public boolean isEmailVerified() {
		return this.emailVerified;
	}

	public void setEmailVerified(boolean emailVerified) {
		this.emailVerified = emailVerified;
	}

	@Column(name = "nickname", length = 45)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "tenant", length = 45)
	public String getTenant() {
		return this.tenant;
	}

	public void setTenant(String tenant) {
		this.tenant = tenant;
	}

	@Column(name = "connection", length = 45)
	public String getConnection() {
		return this.connection;
	}

	public void setConnection(String connection) {
		this.connection = connection;
	}

	@Column(name = "debug", length = 45)
	public String getDebug() {
		return this.debug;
	}

	public void setDebug(String debug) {
		this.debug = debug;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserBranchServicePrivilege> getUserBranchServicePrivileges() {
		return this.userBranchServicePrivileges;
	}

	public void setUserBranchServicePrivileges(
			Set<UserBranchServicePrivilege> userBranchServicePrivileges) {
		this.userBranchServicePrivileges = userBranchServicePrivileges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Queue> getQueues() {
		return this.queues;
	}

	public void setQueues(Set<Queue> queues) {
		this.queues = queues;
	}

}
