package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch", catalog = "heroku_54640e8309ac0d5")
public class Branch implements java.io.Serializable {

	private Integer id;
	private Business business;
	private String name;
	private String location;
	private String gpsLat;
	private String description;
	private int rating;
	private String gpsLong;
	private Set<BranchService> branchServices = new HashSet<BranchService>(0);
	private Set<Employees> employeeses = new HashSet<Employees>(0);

	public Branch() {
	}

	public Branch(int rating) {
		this.rating = rating;
	}

	public Branch(Business business, String name, String location,
			String gpsLat, String description, int rating, String gpsLong,
			Set<BranchService> branchServices, Set<Employees> employeeses) {
		this.business = business;
		this.name = name;
		this.location = location;
		this.gpsLat = gpsLat;
		this.description = description;
		this.rating = rating;
		this.gpsLong = gpsLong;
		this.branchServices = branchServices;
		this.employeeses = employeeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buisness_id")
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "gps_lat", length = 45)
	public String getGpsLat() {
		return this.gpsLat;
	}

	public void setGpsLat(String gpsLat) {
		this.gpsLat = gpsLat;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "gps_long", length = 45)
	public String getGpsLong() {
		return this.gpsLong;
	}

	public void setGpsLong(String gpsLong) {
		this.gpsLong = gpsLong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<BranchService> getBranchServices() {
		return this.branchServices;
	}

	public void setBranchServices(Set<BranchService> branchServices) {
		this.branchServices = branchServices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

}
