package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BuisnessEmployeeRole generated by hbm2java
 */
@Entity
@Table(name = "buisness_employee_role", catalog = "heroku_54640e8309ac0d5")
public class BuisnessEmployeeRole implements java.io.Serializable {

	private Integer id;
	private String name;

	public BuisnessEmployeeRole() {
	}

	public BuisnessEmployeeRole(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
