package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OpeningHour generated by hbm2java
 */
@Entity
@Table(name = "opening_hour", catalog = "heroku_54640e8309ac0d5")
public class OpeningHour implements java.io.Serializable {

	private Integer id;
	private BranchService branchService;
	private Integer day;
	private Date start;
	private Date end;

	public OpeningHour() {
	}

	public OpeningHour(BranchService branchService, Integer day, Date start,
			Date end) {
		this.branchService = branchService;
		this.day = day;
		this.start = start;
		this.end = end;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_service_id")
	public BranchService getBranchService() {
		return this.branchService;
	}

	public void setBranchService(BranchService branchService) {
		this.branchService = branchService;
	}

	@Column(name = "day")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start", length = 0)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end", length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

}
