package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "privilege", catalog = "heroku_54640e8309ac0d5")
public class Privilege implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<EmployeesBranchServicePrivilege> employeesBranchServicePrivileges = new HashSet<EmployeesBranchServicePrivilege>(
			0);
	private Set<UserBranchServicePrivilege> userBranchServicePrivileges = new HashSet<UserBranchServicePrivilege>(
			0);

	public Privilege() {
	}

	public Privilege(
			String name,
			String description,
			Set<EmployeesBranchServicePrivilege> employeesBranchServicePrivileges,
			Set<UserBranchServicePrivilege> userBranchServicePrivileges) {
		this.name = name;
		this.description = description;
		this.employeesBranchServicePrivileges = employeesBranchServicePrivileges;
		this.userBranchServicePrivileges = userBranchServicePrivileges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege")
	public Set<EmployeesBranchServicePrivilege> getEmployeesBranchServicePrivileges() {
		return this.employeesBranchServicePrivileges;
	}

	public void setEmployeesBranchServicePrivileges(
			Set<EmployeesBranchServicePrivilege> employeesBranchServicePrivileges) {
		this.employeesBranchServicePrivileges = employeesBranchServicePrivileges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege")
	public Set<UserBranchServicePrivilege> getUserBranchServicePrivileges() {
		return this.userBranchServicePrivileges;
	}

	public void setUserBranchServicePrivileges(
			Set<UserBranchServicePrivilege> userBranchServicePrivileges) {
		this.userBranchServicePrivileges = userBranchServicePrivileges;
	}

}
