package com.resqueue.models;

// Generated May 9, 2014 8:07:37 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Queue generated by hbm2java
 */
@Entity
@Table(name = "queue", catalog = "heroku_54640e8309ac0d5")
public class Queue implements java.io.Serializable {

	private Integer id;
	private Users users;
	private BranchService branchService;
	private Date queueDate;
	private Integer rating;
	private Integer duration;
	private Integer realDuration;
	private Date realQueueTime;
	private Integer score;
	private String review;
	private Set<Users> userses = new HashSet<Users>(0);

	public Queue() {
	}

	public Queue(Users users, BranchService branchService, Date queueDate,
			Integer rating, Integer duration, Integer realDuration,
			Date realQueueTime, Integer score, String review, Set<Users> userses) {
		this.users = users;
		this.branchService = branchService;
		this.queueDate = queueDate;
		this.rating = rating;
		this.duration = duration;
		this.realDuration = realDuration;
		this.realQueueTime = realQueueTime;
		this.score = score;
		this.review = review;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_service_id")
	public BranchService getBranchService() {
		return this.branchService;
	}

	public void setBranchService(BranchService branchService) {
		this.branchService = branchService;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "queue_date", length = 0)
	public Date getQueueDate() {
		return this.queueDate;
	}

	public void setQueueDate(Date queueDate) {
		this.queueDate = queueDate;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "real_duration")
	public Integer getRealDuration() {
		return this.realDuration;
	}

	public void setRealDuration(Integer realDuration) {
		this.realDuration = realDuration;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "real_queue_time", length = 0)
	public Date getRealQueueTime() {
		return this.realQueueTime;
	}

	public void setRealQueueTime(Date realQueueTime) {
		this.realQueueTime = realQueueTime;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "review", length = 140)
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queue")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
